export interface Team {

    id: number,
    name: String,
    code: String,
    form: String,
    wins_local_games: number,
    draws_local_games: number,
    loses_local_games: number,
    wins_visitor_games: number,
    draws_visitor_games: number,
    loses_visitor_games: number,
    favour_local_goals: number,
    favour_visitor_goals: number,
    against_local_goals: number,
    against_visitor_goals: number,
    favour_goals_0_15: number,
    favour_goals_16_30: number,
    favour_goals_31_45: number,
    favour_goals_46_60: number,
    favour_goals_61_75: number,
    favour_goals_76_90: number,
    against_goals_0_15: number,
    against_goals_16_30: number,
    against_goals_31_45: number,
    against_goals_46_60: number,
    against_goals_61_75: number,
    against_goals_76_90: number,
    local_clean_sheets: number,
    visitor_clean_sheets: number,
    local_failed_to_score: number,
    visitor_failed_to_score: number,
    total_yellow_cards: number,
    total_red_cards: number,
}